wa_flickr_homepage:
    path:     /contact
    defaults: { _controller: WAFlickrBundle:Contact:index }
    requirements:
        _method: GET

wa_flickr_save:
    path:     /contact
    defaults: { _controller: WAFlickrBundle:Contact:save }
    requirements:
        _method: POST

wa_flickr_home:
    path:     /search
    defaults: { _controller: WAFlickrBundle:Search:index }
    requirements:
        _method: GET

wa_flickr_search:
    path:     /search
    defaults: { _controller: WAFlickrBundle:Search:search}
    requirements:
        _method: POST

wa_flickr_photomore:
    path:     /search/photo/{farm}/{id}/{secret}/{server}
    defaults: { _controller: WAFlickrBundle:Search:photomore}






